export const APP_VERSION = "7.3.1"

export enum AccountKind {
  STUDENT
}

export enum Gender {
  MALE,
  FEMALE,
  NOT_SPECIFIED
}

export enum Permissions {
  HUB,
  FORMS,
  GRADES,
  QUIZZES,
  MESSAGING,
  TIMETABLE,
  HOMEWORKS,
  ATTENDANCE,
  CLASS_LIFE,
  ENABLE_2FA,
  CLOUD_DRIVE,
  SCHOOL_BOOKS,
  CLASS_JOURNAL,
  MEAL_ORDERING,
  CFA_ATTENDANCE,
  CANTEEN_BARCODE,
  FINANCIAL_STATUS,
  STUDENT_DOCUMENTS,
  ROBERT_DICTIONNARY,
  CANTEEN_RESERVATION,
  CORRESPONDENCE_BOOK,
  INTERNSHIP_TRACKING,
  APPRENTICESHIP_RECORD,
  PARENT_TEACHER_MEETINGS,
}
